name: main

on:
  schedule:
    - cron: "0 12 * * MON,TUE,WED,THU,FRI"
  push:
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python3 get_menu.py
      - name: Deply
        run: |
          git config --local user.email "nakano57@users.noreply.github.com"
          git config --local user.name "nakano57-bot"
          git add menu.csv
          git commit -m "Update data"
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
